// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5053.FRC2016Stronghold.subsystems;

import org.usfirst.frc5053.FRC2016Stronghold.RobotMap;
import org.usfirst.frc5053.FRC2016Stronghold.commands.*;
import java.util.Date;
import edu.wpi.first.wpilibj.AnalogGyro;
//import edu.wpi.first.wpilibj.Gyro;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Navigation extends Subsystem {
	
	public final static String areaOfField(double x, double y) {
		if ((y>410.5) && (y<=458.5)){
			if (x<=53.1) {
				return "Their D1";
			}
				else if (x<=106.2){
					return "Their D2";
			}
				else if (x<=159.3){
					return "Their D3";
			}
				else if (x<=212.4){
					return "Their D4";
			}
				else if (x<=265.5){
					return "Their D5";
			}
				else if (x<=319){
					return "Their Secret Passage";
			}
	}
				//Their Courtyard
		if ((y>458.5) && (y<=650)){
			if (x<=265.5){
				return "Their Courtyard";
				}
				else if (x<=319){
					return "Their Secret Passage";
				}
		}
			//Their Neutral Zone
		if ((y>362.5) && (y<=410.5)){
			if (x<=265.5){
				return "Their Neutral";
			}
			else if (x<=319){
				return "Their Secret Passage";
			}
			//Neutral
	if ((y>287.5) && (y<=362.5)){
		return "Neutral";
	}
		};
	//Our Neutral
	if ((y>239.5) && (y<=287.5)){
		if (x<=53.1){
			return "Our Secret Passage";
		}
		else if (x<=319){
			return "Our Neutral";
		}
		//Our Defenses
	}
		if ((y>191.5) && (y<=239.5)){
			if (x<=53.1) {
				return "Their D1";
			}
				else if (x<=106.2){
					return "Their D2";
			}
				else if (x<=159.3){
					return "Their D3";
			}
				else if (x<=212.4){
					return "Their D4";
			}
				else if (x<=265.5){
					return "Their D5";
				}
				else if (x<=319){
					return "Their Secret Passage";
				}
		}
		if ((y>0) && (y<=191.5)){
			if (x<=53.1){
				return "Our Secret Passage";
			}
			else if (x<=310){
				return "Our Courtyard";
			}
		}
		return "Error";
			}

	
	
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final AnalogGyro oldAnalogGyro = RobotMap.navigationoldAnalogGyro;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new AllwaysTrackLocation());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }



public static void main(String args[]) {
}
}
