// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5053.FRC2016Stronghold;

import org.usfirst.frc5053.FRC2016Stronghold.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;
import org.usfirst.frc5053.FRC2016Stronghold.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton shooterSlow;
    public JoystickButton driveStrightPID;
    public JoystickButton shooter;
    public JoystickButton shooterOff;
    public JoystickButton spinKickShooter;
    public JoystickButton joystickButton1;
    public JoystickButton kickerDriver;
    public JoystickButton driveStraightAtTargetButton;
    public JoystickButton fieldOrientToPOVButtons;
    public Joystick driver;
    
    public JoystickButton intakeSpin;
    public JoystickButton intakeSpinOff;
    public JoystickButton intakeReverse;
    public JoystickButton intakeReverseOff;
    public JoystickButton intakeReverseFast;
    public JoystickButton intakeReverseFastOff;
    public JoystickButton scalerReach;
    public JoystickButton armNeutral;
    public JoystickButton armGetBall;
    public JoystickButton armLiftPorticullis;
    public JoystickButton armScale;
    public JoystickButton arcadeArm;
    public JoystickButton shooterIntake;
    public JoystickButton shooterIntakeOff;
    public Joystick operator;
    
    public JoystickButton debugForShooterAim;
    public JoystickButton debugForShooterAimPID;
    public Joystick debugJoystick;
    
    public Joystick driverMap2;
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    	
    	driverMap2 = new Joystick(3);
        
        fieldOrientToPOVButtons = new JoystickButton(driverMap2, 8);
        fieldOrientToPOVButtons.whileHeld(new DriveRotateFieldOrientation());
        driveStraightAtTargetButton = new JoystickButton(driverMap2, 5);
        driveStraightAtTargetButton.whileHeld(new DriveStraighToTarget());
        kickerDriver = new JoystickButton(driverMap2, 6);
        kickerDriver.whileHeld(new ScalerReachUp());
        joystickButton1 = new JoystickButton(driverMap2, 4);
        joystickButton1.whenReleased(new ShooterSpin(0));
        spinKickShooter = new JoystickButton(driverMap2, 4);
        spinKickShooter.whileHeld(new PneumaticsShooterKick());
        shooterOff = new JoystickButton(driverMap2, 2);
        shooterOff.whenReleased(new ShooterSpin(0));
        shooter = new JoystickButton(driverMap2, 2);
        shooter.whileHeld(new ShooterSpin(2000));
        driveStrightPID = new JoystickButton(driverMap2, 3);
        driveStrightPID.whileHeld(new ArcadeDriveStrightPID());
        shooterSlow = new JoystickButton(driverMap2, 1);
        shooterSlow.whileHeld(new ShooterSpin(-1500));
    	
    	debugJoystick = new Joystick(2);
    	
    	debugForShooterAim = new JoystickButton(debugJoystick, 1);
        debugForShooterAim.whileHeld(new ArcadeShooterAimControl());
    	debugForShooterAimPID = new JoystickButton(debugJoystick, 2);
        debugForShooterAimPID.whileHeld(new ShooterAimSetpoints(10));
    	
        operator = new Joystick(1);
        
        arcadeArm = new JoystickButton(operator, 1);
        arcadeArm.whileHeld(new ArcadeArmControl());
        intakeReverseOff = new JoystickButton(operator, 2);
        intakeReverseOff.whenReleased(new SpinIntake(0));
        intakeReverse = new JoystickButton(operator, 2);
        intakeReverse.whileHeld(new ShooterSpinIntake());
        intakeReverseFastOff = new JoystickButton(operator, 3);
        intakeReverseFastOff.whenReleased(new SpinIntake(0));
        intakeReverseFast = new JoystickButton(operator, 3);
        intakeReverseFast.whileHeld(new ShooterSpinIntakeFast());
        intakeSpinOff = new JoystickButton(operator, 4);
        intakeSpinOff.whenReleased(new SpinIntake(0));
        intakeSpin = new JoystickButton(operator, 4);
        intakeSpin.whileHeld(new SpinIntake(1));
        scalerReach = new JoystickButton(operator, 5);
        scalerReach.whileHeld(new ScalerReachUp());
        armNeutral = new JoystickButton(operator, 6);
        armNeutral.whileHeld(new ArmSetpoints(0.209));
        armGetBall = new JoystickButton(operator, 7);
        armGetBall.whileHeld(new ArmSetpoints(0.334));
        armLiftPorticullis = new JoystickButton(operator, 8);
        armLiftPorticullis.whileHeld(new ArmSetpoints(0.348));
        armScale = new JoystickButton(operator, 9);
        armScale.whileHeld(new ArmSetpoints(0.209));
        shooterIntakeOff = new JoystickButton(operator, 10);
        shooterIntakeOff.whenReleased(new ShooterSpin(0));
        shooterIntake = new JoystickButton(operator, 10);
        shooterIntake.whileHeld(new ShooterSpin(-750));
        
        
        
        driver = new Joystick(0);
        
        fieldOrientToPOVButtons = new JoystickButton(driver, 8);
        fieldOrientToPOVButtons.whileHeld(new DriveRotateFieldOrientation());
        driveStraightAtTargetButton = new JoystickButton(driver, 5);
        driveStraightAtTargetButton.whileHeld(new DriveStraighToTarget());
        kickerDriver = new JoystickButton(driver, 6);
        kickerDriver.whileHeld(new ScalerReachUp());
        joystickButton1 = new JoystickButton(driver, 4);
        joystickButton1.whenReleased(new ShooterSpin(0));
        spinKickShooter = new JoystickButton(driver, 4);
        spinKickShooter.whileHeld(new PneumaticsShooterKick());
        shooterOff = new JoystickButton(driver, 2);
        shooterOff.whenReleased(new ShooterSpin(0));
        shooter = new JoystickButton(driver, 2);
        shooter.whileHeld(new ShooterSpin(2000));
        driveStrightPID = new JoystickButton(driver, 3);
        driveStrightPID.whileHeld(new ArcadeDriveStrightPID());
        shooterSlow = new JoystickButton(driver, 1);
        shooterSlow.whileHeld(new ShooterSpin(-1500));
        
        // SmartDashboard Buttons
        SmartDashboard.putData("ArcadeShooterAimControl", new ArcadeShooterAimControl());
        SmartDashboard.putData("ShooterAimSetpoints: LowGoal", new ShooterAimSetpoints(0));
        SmartDashboard.putData("ShooterAimSetpoints: FarLowGoal", new ShooterAimSetpoints(0));
        SmartDashboard.putData("ShooterAimSetpoints: SetHighGoal", new ShooterAimSetpoints(0));
        SmartDashboard.putData("RobotCanSee", new RobotCanSee());
        SmartDashboard.putData("AutonSelection", new AutonSelection());
        SmartDashboard.putData("ArmSetpoints: Neutral", new ArmSetpoints(0.209));
        SmartDashboard.putData("ArmSetpoints: GetBall", new ArmSetpoints(0.334));
        SmartDashboard.putData("ArmSetpoints: LiftPorticullis", new ArmSetpoints(0.348));
        SmartDashboard.putData("ArmSetpoints: Scale", new ArmSetpoints(0.209));
        SmartDashboard.putData("ArmSetpoints: AutonPos", new ArmSetpoints(0.300));
        SmartDashboard.putData("ArcadeArmControl", new ArcadeArmControl());
        SmartDashboard.putData("Auton: LowBarLefGoal", new Auton(1, "Left", "Low"));
        SmartDashboard.putData("Auton: LowBarRightGoal", new Auton(1, "Right", "Low"));
        SmartDashboard.putData("ArcadeDrive", new ArcadeDrive());
        SmartDashboard.putData("ArcadeDriveStraight", new ArcadeDriveStraight());
        SmartDashboard.putData("ArcadeDriveStrightPID", new ArcadeDriveStrightPID());
        SmartDashboard.putData("DriveForward: default", new DriveForward(50));
        SmartDashboard.putData("DriveSpin", new DriveSpin());
        SmartDashboard.putData("SpinIntake: Forward", new SpinIntake(1));
        SmartDashboard.putData("SpinIntake: Reverse", new SpinIntake(-0.5));
        SmartDashboard.putData("SpinIntake: Stop", new SpinIntake(0));
        SmartDashboard.putData("SpinIntake: ReverseFast", new SpinIntake(-1));
        SmartDashboard.putData("SquareDrive", new SquareDrive());
        SmartDashboard.putData("ScalerReachUp", new ScalerReachUp());
        SmartDashboard.putData("KickBall", new KickBall());
        SmartDashboard.putData("ShooterSpin: Default", new ShooterSpin(2000));
        SmartDashboard.putData("ShooterSpin: Off", new ShooterSpin(0));
        SmartDashboard.putData("ShooterSpin: Intake", new ShooterSpin(-750));
        SmartDashboard.putData("ShooterSpin: SlowShoot", new ShooterSpin(-500));
        SmartDashboard.putData("CrossRoughTerrain: forward", new CrossRoughTerrain(1));
        SmartDashboard.putData("CrossRockWall: forward", new CrossRockWall(1));
        SmartDashboard.putData("CrossRamparts: forward", new CrossRamparts(1));
        SmartDashboard.putData("CrossMoat: forward", new CrossMoat(1));
        SmartDashboard.putData("CrossLowBar: forward", new CrossLowBar(1));
        SmartDashboard.putData("CrossDrawbridge: forward", new CrossDrawbridge(1));
        SmartDashboard.putData("CrossPorticullis: forward", new CrossPorticullis(1));
        SmartDashboard.putData("CrossChevalDeFrise: forward", new CrossChevalDeFrise(1));
        SmartDashboard.putData("LowBarAuton", new LowBarAuton());
        SmartDashboard.putData("KickOff", new KickOff());
        SmartDashboard.putData("PneumaticsShooterKick", new PneumaticsShooterKick());
        SmartDashboard.putData("ShooterSpinIntake", new ShooterSpinIntake());
        SmartDashboard.putData("TestDrive10Ft", new TestDrive10Ft());
        SmartDashboard.putData("DriveStraighToTarget", new DriveStraighToTarget());
        SmartDashboard.putData("DriveRotateFieldOrientation", new DriveRotateFieldOrientation());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getDriver() {
        return driver;
    }

    public Joystick getOperator() {
        return operator;
    }
    
    public Joystick getDebugJoystick() {
    	return debugJoystick;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

