// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5053.FRC2016Stronghold;

import edu.wpi.first.wpilibj.IterativeRobot;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.networktables.NetworkTable;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc5053.FRC2016Stronghold.commands.*;
import org.usfirst.frc5053.FRC2016Stronghold.subsystems.*;

import edu.wpi.first.wpilibj.CameraServer;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the IterativeRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the manifest file in the resource
 * directory.
 */
public class Robot extends IterativeRobot {

    Command autonomousCommand;

    public static OI oi;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static VisionHandler visionHandler;
    public static DriveTrain driveTrain;
    public static LeftShooter leftShooter;
    public static RightShooter rightShooter;
    public static Intake intake;
    public static ScalingExtend scalingExtend;
    public static Arm arm;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CameraServer camera = CameraServer.getInstance();

    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
    public void robotInit() {
    RobotMap.init();
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        visionHandler = new VisionHandler();
        driveTrain = new DriveTrain();
        leftShooter = new LeftShooter();
        rightShooter = new RightShooter();
        intake = new Intake();
        scalingExtend = new ScalingExtend();
        arm = new Arm();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // OI must be constructed after subsystems. If the OI creates Commands
        //(which it very likely will), subsystems are not guaranteed to be
        // constructed yet. Thus, their requires() statements may grab null
        // pointers. Bad news. Don't move it.
        oi = new OI();

        // instantiate the command used for the autonomous period
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

        autonomousCommand = new AutonSelection();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
        
        //camera.setQuality(50);
      //  camera.setSize(1/*camera.kSize320x240*/); 
        //        camera.setImage(Image.SCALE_FAST);
        //camera.startAutomaticCapture("cam0");
    }

	public static MotionControlPIDController createRotationPIDController(double targetAngle, double start, PIDOutput pidOutput) {
		
	    double     ramp =  30; //degrees
	    double maxspeed = 10.0*(360/60) ; //60/360 converts the first numbers which is in RPM to degrees/second
		
		final double Kp = 1d/200; // so at denominator off in the spin-Rate the power will reach the max
	    final double Ki = 0.0000;
	    final double Kd = 0.0;
	 
	    MotionControlPIDController localRotationSpeedPID;

	    MotionControlHelper rotationSpeedProfile; 
        rotationSpeedProfile = new MotionControlHelper(targetAngle, ramp, maxspeed, start, (PIDSource) RobotMap.gyroToUse, pidOutput);
        localRotationSpeedPID = new MotionControlPIDController(Kp,Ki,Kd, rotationSpeedProfile );
        localRotationSpeedPID.setOutputRange(-1.0, 1.0);
        localRotationSpeedPID.enable();
	    return localRotationSpeedPID;
	}
	
    /**
     * This function is called when the disabled button is hit.
     * You can use it to reset subsystems before shutting down.
     */
    public void disabledInit(){

    }

    public void disabledPeriodic() {
        Scheduler.getInstance().run();
    }

    public void autonomousInit() {
       // navigation.autonomousInit();
    	int startPosition = SmartDashboard.getInt("Start Position");
    	
    	// What Defense is in front of us?
    	String defenseType = "Low bar";
    	try{
//	    	DefenseNameString = SmartDashboard.getString("Defence Name ");
	    	NetworkTable networkTable = NetworkTable.getTable("SmartDashboard");
	    	String[] defenseNames = networkTable.getStringArray("Defence Name");
	    	defenseType =defenseNames[startPosition]; 
    	}catch (Exception e){e.printStackTrace();};
//	    String DefenseNameString = SmartDashboard.
	    
    	try{
// Should work with newest code running on front dashboard	    
    	switch(startPosition){
    		case 2: defenseType = SmartDashboard.getString("Defense 2"); break;
    		case 3: defenseType = SmartDashboard.getString("Defense 3"); break;
    		case 4: defenseType = SmartDashboard.getString("Defense 4"); break;
    		case 5: defenseType = SmartDashboard.getString("Defense 5"); break;
    	}
    	}catch (Exception e){e.printStackTrace();};
	    System.out.println("Defence Name String = '"+defenseType+"'");

	    int defense = AutonSelection.LOW_BAR;
    	if(defenseType.equals("Rock Wall"    )) {defense = AutonSelection.ROCK_WALL;}
    	if(defenseType.equals("Rough Terrain")) {defense = AutonSelection.ROUGH_TERRAIN;}
    	if(defenseType.equals("Chilli Fries" )) {defense = AutonSelection.CHEVAL_DE_FRISE;}
    	if(defenseType.equals("Porticullis"  )) {defense = AutonSelection.PORTICULLIS;}
    	if(defenseType.equals("Moat"         )) {defense = AutonSelection.MOAT;}
    	if(defenseType.equals("Ramparts"     )) {defense = AutonSelection.RAMPARTS;}
    	if(defenseType.equals("Sally Port"   )) {defense = AutonSelection.SALLY_PORT;}
    	if(defenseType.equals("Drawbridge"   )) {defense = AutonSelection.DRAWBRIDGE;}

    	
    	// Are we going for Left Center or Right goal?
    	//-----------------------------------------------------------------------
    	int goalSide = AutonSelection.LEFT_GOAL; // "Goal Position" // TEMP
    	String goalPosition = "Left";
    	try{
	    	goalPosition = SmartDashboard.getString("Goal Position");
    	}catch (Exception e){e.printStackTrace();};
    	if(("Right" ).equals(goalPosition))goalSide=AutonSelection.RIGHT_GOAL;
    	if(("Center").equals(goalPosition))goalSide=AutonSelection.CENTER_GOAL;
    	if(("Left"  ).equals(goalPosition))goalSide=AutonSelection.LEFT_GOAL;//Note defaults to Left (orginally assignment) if no valid value provided
    	
    	System.out.println("GoalPosition = '"+goalPosition+"   foalSide='"+goalSide+"'   ");

    	// Are we going for High or Low goal?
    	//-----------------------------------------------------------------------
    	int goalHeight = AutonSelection.LOW_GOAL; //"Goal High Low" //TEMP
	    String goalHeightString = "";
    	try{
    		goalHeightString = SmartDashboard.getString("Goal High Low");
    	}catch (Exception e){e.printStackTrace();};
    	System.out.println("GoalHeight = '"+goalHeightString);
    	if(("Low"  ).equals(goalHeightString))goalHeight=AutonSelection.LOW_GOAL;
    	if(("Right").equals(goalHeightString))goalHeight=AutonSelection.HIGH_GOAL;
    	
    	if(autonomousCommand instanceof AutonSelection  ){
    		AutonSelection autonSelection =(AutonSelection) autonomousCommand;
    		autonSelection.setAuton(startPosition, defense, goalSide, goalHeight);
    	}
    	System.out.println("GoalHeightString = '"+goalHeightString+"  goalHeight='"+goalHeight+"'    ");
        // schedule the autonomous command (example)
        if (autonomousCommand != null) autonomousCommand.start();
    }

    /**
     * This function is called periodically during autonomous
     */
    public void autonomousPeriodic() {
        Scheduler.getInstance().run();
    }

    public void teleopInit() {
        // This makes sure that the autonomous stops running when
        // teleop starts running. If you want the autonomous to
        // continue until interrupted by another command, remove
        // this line or comment it out.
        if (autonomousCommand != null) autonomousCommand.cancel();
    }

    /**
     * This function is called periodically during operator control
     */
    public void teleopPeriodic() {
        Scheduler.getInstance().run();
    }

    /**
     * This function is called periodically during test mode
     */
    public void testPeriodic() {
        LiveWindow.run();
    }
}
