// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5053.FRC2016Stronghold.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc5053.FRC2016Stronghold.Robot;
import org.usfirst.frc5053.FRC2016Stronghold.RobotMap;
import org.usfirst.frc5053.FRC2016Stronghold.TalonCurrentLimited;

/**
 *
 */
public class ShooterAimLimitSwitch extends Command {

	public boolean highOrLow;

    public ShooterAimLimitSwitch(boolean highOrLow) {
    	this.highOrLow = highOrLow;
        requires(Robot.shooterAim);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    if(highOrLow) {
    	RobotMap.shooterAimShooterAimMotor.set(.40);
    	
    }
    else {
    	RobotMap.shooterAimShooterAimMotor.set(-.70);
    }
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    if(TalonCurrentLimited.pdp.getCurrent(3) > .75) {
    	return true;
    }
    else {
    	return false;
    }
}
    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	RobotMap.shooterAimShooterAimMotor.set(0);
    }
}
