// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5053.FRC2016Stronghold.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc5053.FRC2016Stronghold.subsystems.*;

/**
 *
 */
public class VisionAlignForHighGoalShot extends CommandGroup {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public VisionAlignForHighGoalShot() {

    	System.out.println("VisionAlignForHighGoalShoot constructore setting up Commands for Goal Alignment");
    	addSequential( new DriveRotateToGoal());
    	addSequential(new ShooterAimToHighGoal());
 
    	
    }



}
